export { default as Home } from './Home';
export { default as CommunityFeed } from './CommunityFeed';
export { default as Post } from './Post';
export { default as Community } from './Community';
export { default as Diary } from './Diary';
export { default as Mypage } from './Mypage';
export { default as Userpage } from './Userpage';
export { default as HosInfo } from './Info/HosInfo';
export { default as PharInfo } from './Info/PharInfo';